### ISSUE TITLE
Encoding error python3.10 & JSONDecodeError on python 3.8

### ISSUE THREAD

**Issue by just-rich** [JoaoAlvaroFerreira/TweetDelete#1]
not sure how to fix it. 

Python 3.10.10
`Traceback (most recent call last):
  File "/home/th/test/tweetdelete/tweetdelete.py", line 108, in <module>
    main()
  File "/home/th/test/tweetdelete/tweetdelete.py", line 101, in main
    oauth = auth()
  File "/home/th/test/tweetdelete/tweetdelete.py", line 34, in auth
    data = json.load(f, encoding="utf8")
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'`

Python 3.8.10
`Traceback (most recent call last):
  File "tweetdelete.py", line 108, in <module>
    main()
  File "tweetdelete.py", line 102, in main
    tweets = loadTweets()
  File "tweetdelete.py", line 22, in loadTweets
    tweets = json.load(f, encoding="utf8")
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tonmoygoswami** [comment]
I can solve this error for you. Just rename `tweet.js` and `tweet.json` to `tweets.js` and `tweets.json`

**Comment by Asem-Ashraf** [comment]
the encoding step is moved to the open function rather than the json.load function
